# Generated by Django 4.2.9 on 2026-02-15 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HARImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_path', models.CharField(max_length=500, verbose_name='文件路径')),
                ('resource_types', models.JSONField(default=list, verbose_name='资源类型过滤')),
                ('host_replacement', models.CharField(blank=True, max_length=500, null=True, verbose_name='Host替换')),
                ('imported_count', models.IntegerField(default=0, verbose_name='导入请求数')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'HAR导入记录',
                'verbose_name_plural': 'HAR导入记录',
                'db_table': 'har_imports',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='请求名称')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='请求URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body_type', models.CharField(choices=[('none', '无'), ('json', 'JSON'), ('form', '表单'), ('file', '文件')], default='none', max_length=10, verbose_name='请求体类型')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('weight', models.IntegerField(default=1, verbose_name='权重')),
                ('think_time', models.FloatField(default=1.0, verbose_name='思考时间(秒)')),
                ('timeout', models.IntegerField(default=30, verbose_name='超时时间(秒)')),
                ('datasource_mapping', models.JSONField(blank=True, default=dict, verbose_name='数据源映射')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '请求',
                'verbose_name_plural': '请求',
                'db_table': 'requests',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='场景名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='场景描述')),
                ('is_imported_from_har', models.BooleanField(default=False, verbose_name='是否从HAR导入')),
                ('har_file_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='HAR文件名')),
                ('default_users', models.IntegerField(default=10, verbose_name='默认用户数')),
                ('default_spawn_rate', models.IntegerField(default=1, verbose_name='默认每秒生成用户数')),
                ('default_duration', models.IntegerField(default=60, verbose_name='默认压测时长(秒)')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '压测场景',
                'verbose_name_plural': '压测场景',
                'db_table': 'scenarios',
                'ordering': ['-created_at'],
            },
        ),
    ]
