# Generated by Django 4.2.9 on 2026-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenarios', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenario',
            name='target_host',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='目标Host'),
        ),
    ]
