# Generated by Django 4.2.9 on 2026-02-15 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='数据源名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('source_type', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('mongodb', 'MongoDB'), ('redis', 'Redis'), ('python', 'Python脚本')], max_length=20, verbose_name='数据源类型')),
                ('file_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='文件路径')),
                ('file_encoding', models.CharField(default='utf-8', max_length=20, verbose_name='文件编码')),
                ('csv_delimiter', models.CharField(default=',', max_length=10, verbose_name='CSV分隔符')),
                ('db_host', models.CharField(blank=True, max_length=255, null=True, verbose_name='主机')),
                ('db_port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('db_user', models.CharField(blank=True, max_length=100, null=True, verbose_name='用户名')),
                ('db_password', models.CharField(blank=True, max_length=255, null=True, verbose_name='密码')),
                ('db_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='数据库名')),
                ('db_query', models.TextField(blank=True, null=True, verbose_name='查询语句')),
                ('db_collection', models.CharField(blank=True, max_length=100, null=True, verbose_name='集合/表名')),
                ('redis_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redis键')),
                ('redis_pattern', models.CharField(blank=True, max_length=255, null=True, verbose_name='Redis匹配模式')),
                ('python_script', models.TextField(blank=True, null=True, verbose_name='Python脚本')),
                ('preview_data', models.JSONField(blank=True, default=list, verbose_name='预览数据')),
                ('total_count', models.IntegerField(default=0, verbose_name='数据总数')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'datasources',
            },
        ),
    ]
