# Generated by Django 4.2.9 on 2026-02-15 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Environment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='环境名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='环境描述')),
                ('is_default', models.BooleanField(default=False, verbose_name='是否默认环境')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '环境',
                'verbose_name_plural': '环境',
                'db_table': 'environments',
            },
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='变量名')),
                ('value', models.TextField(verbose_name='变量值')),
                ('var_type', models.CharField(choices=[('text', '文本'), ('secret', '敏感'), ('reference', '引用')], default='text', max_length=20, verbose_name='变量类型')),
                ('scope', models.CharField(choices=[('global', '全局'), ('project', '项目'), ('scenario', '场景')], default='global', max_length=20, verbose_name='作用域')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('environment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variables', to='environments.environment')),
            ],
            options={
                'verbose_name': '变量',
                'verbose_name_plural': '变量',
                'db_table': 'variables',
            },
        ),
    ]
