# Generated by Django 4.2.9 on 2026-02-15 00:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='断言名称')),
                ('assertion_type', models.CharField(choices=[('status_code', '状态码'), ('response_time', '响应时间'), ('json_path', 'JSON路径'), ('regex', '正则匹配'), ('contains', '包含验证'), ('numeric_range', '数值范围')], max_length=20, verbose_name='断言类型')),
                ('target_path', models.CharField(blank=True, max_length=500, null=True, verbose_name='目标路径（JSON Path）')),
                ('expected_value', models.TextField(verbose_name='预期值')),
                ('operator', models.CharField(choices=[('eq', '等于'), ('ne', '不等于'), ('gt', '大于'), ('gte', '大于等于'), ('lt', '小于'), ('lte', '小于等于'), ('contains', '包含'), ('regex', '匹配正则')], default='eq', max_length=20, verbose_name='操作符')),
                ('min_value', models.FloatField(blank=True, null=True, verbose_name='最小值')),
                ('max_value', models.FloatField(blank=True, null=True, verbose_name='最大值')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '断言规则',
                'verbose_name_plural': '断言规则',
                'db_table': 'assertions',
            },
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='用例名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE'), ('PATCH', 'PATCH')], default='GET', max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='请求URL')),
                ('headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('order', models.IntegerField(default=0, verbose_name='排序')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测试用例',
                'verbose_name_plural': '测试用例',
                'db_table': 'test_cases',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('passed', '通过'), ('failed', '失败'), ('error', '错误')], max_length=20, verbose_name='状态')),
                ('request_headers', models.JSONField(blank=True, default=dict, verbose_name='请求头')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='请求体')),
                ('response_status', models.IntegerField(verbose_name='响应状态码')),
                ('response_headers', models.JSONField(blank=True, default=dict, verbose_name='响应头')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='响应体')),
                ('response_time', models.FloatField(verbose_name='响应时间(ms)')),
                ('assertion_results', models.JSONField(default=list, verbose_name='断言结果')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '测试结果',
                'verbose_name_plural': '测试结果',
                'db_table': 'test_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TestSuite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='套件名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '测试套件',
                'verbose_name_plural': '测试套件',
                'db_table': 'test_suites',
            },
        ),
    ]
