[tool:pytest]
DJANGO_SETTINGS_MODULE = config.settings
python_files = tests.py test_*.py *_tests.py
addopts = -ra -q
testpaths = 
    apps/tests.py
    apps/users/tests
    apps/reports/tests
    apps/scenarios/tests
    apps/environments/tests
    apps/datasources/tests
    apps/api_tests/tests
markers =
    integration: marks tests as integration tests
    unit: marks tests as unit tests
    slow: marks tests as slow