# Generated by Django 4.2.9 on 2026-02-15 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', '管理员'), ('user', '普通用户'), ('viewer', '只读用户')], default='user', max_length=20),
        ),
    ]
