# Generated by Django 4.2.9 on 2026-02-15 00:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='报告名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='报告描述')),
                ('users', models.IntegerField(verbose_name='并发用户数')),
                ('spawn_rate', models.IntegerField(verbose_name='每秒生成用户数')),
                ('duration', models.IntegerField(verbose_name='压测时长(秒)')),
                ('status', models.CharField(choices=[('pending', '待运行'), ('running', '运行中'), ('completed', '已完成'), ('failed', '失败'), ('stopped', '已停止')], default='pending', max_length=20, verbose_name='状态')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('ended_at', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('total_requests', models.BigIntegerField(default=0, verbose_name='总请求数')),
                ('total_failures', models.BigIntegerField(default=0, verbose_name='失败请求数')),
                ('success_rate', models.FloatField(default=0, verbose_name='成功率(%)')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(default=0, verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='最大响应时间(ms)')),
                ('p50_response_time', models.FloatField(default=0, verbose_name='P50响应时间(ms)')),
                ('p90_response_time', models.FloatField(default=0, verbose_name='P90响应时间(ms)')),
                ('p95_response_time', models.FloatField(default=0, verbose_name='P95响应时间(ms)')),
                ('p99_response_time', models.FloatField(default=0, verbose_name='P99响应时间(ms)')),
                ('rps', models.FloatField(default=0, verbose_name='RPS')),
                ('error_distribution', models.JSONField(default=dict, verbose_name='错误分布')),
                ('stats_file', models.CharField(blank=True, max_length=500, null=True, verbose_name='统计数据文件')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '压测报告',
                'verbose_name_plural': '压测报告',
                'db_table': 'reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request_name', models.CharField(max_length=200, verbose_name='请求名称')),
                ('method', models.CharField(max_length=10, verbose_name='请求方法')),
                ('url', models.TextField(verbose_name='请求URL')),
                ('num_requests', models.BigIntegerField(default=0, verbose_name='请求数')),
                ('num_failures', models.BigIntegerField(default=0, verbose_name='失败数')),
                ('avg_response_time', models.FloatField(default=0, verbose_name='平均响应时间(ms)')),
                ('min_response_time', models.FloatField(default=0, verbose_name='最小响应时间(ms)')),
                ('max_response_time', models.FloatField(default=0, verbose_name='最大响应时间(ms)')),
                ('p50_response_time', models.FloatField(default=0, verbose_name='P50响应时间(ms)')),
                ('p90_response_time', models.FloatField(default=0, verbose_name='P90响应时间(ms)')),
                ('p95_response_time', models.FloatField(default=0, verbose_name='P95响应时间(ms)')),
                ('p99_response_time', models.FloatField(default=0, verbose_name='P99响应时间(ms)')),
                ('response_time_distribution', models.JSONField(default=dict, verbose_name='响应时间分布')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_stats', to='reports.report')),
            ],
            options={
                'verbose_name': '请求统计',
                'verbose_name_plural': '请求统计',
                'db_table': 'request_stats',
            },
        ),
    ]
